image: gitpod/workspace-full-vnc
tasks:
  - init: npm install -g @angular/cli && npm install && sudo apt-get install -y --no-install-recommends chromium-browser
  - command: sleep 30;code --install-extension kyntrack.revpro-karma-test-explorer
